### ISSUE TITLE
add actual rename button

### ISSUE THREAD

**Issue by itsplux** [Xytrizareal/uploading-service#1]
**Is your feature request related to a problem? Please describe.**
Sometimes. You have to rename the file and reupload it every time u rename.

**Describe the solution you'd like**
A Rename image button.

**Describe alternatives you've considered**
Reuploading the same file with diffrent name.

**Additional context**
Add any other context or screenshots about the feature request here.(Dont have any)

**Comment by Xytrizareal** [comment]
hm okay :)
